spring.cloud.stream:
  function:
    definition: domainProcessor
  bindings:
    domainProcessor-in-0:
      destination: web-domains-topic
    domainProcessor-out-0:
      destination: active.web-domains-topic
  kafka:
    bindings:
      domainProcessor-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      domainProcessor-out-0:
        producer:
          configuration:
            value:
              serializer: org.springframework.kafka.support.serializer.JsonSerializer
    binder:
      brokers:
        - localhost:9091
        - localhost:9092